services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    env_file:
      - ./app/.env
    volumes:
      - ./local/logs/javaApp:/logs
    depends_on:
      database:
        condition: service_healthy

  database:
    image: "postgres:latest"
    ports:
      - "5432:5432"  # maps container port 5432 to host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db-data:/var/lib/postgresql # persist data outside the container
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  script:
    build:
      context: ./collectDataContainer
      dockerfile: Dockerfile.script
    volumes:
      - ./local/storesData/backup:/storesData/backup
      - ./local/storesData/stores:/storesData/stores
      - ./local/logs:/logs
    restart: unless-stopped



