FROM python:3.11-slim

RUN apt-get update && apt-get install -y cron postgresql-client

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./Scripts/Extract/getData.py .
COPY ./Scripts/Import/importCSV.sh .
COPY ./Scripts/runScript.sh .
COPY ./Scripts/Import/import_csv.py .
COPY ./Scheduler/crontab /etc/cron.d/python-cron

RUN chmod 0644 /etc/cron.d/python-cron
RUN chmod a+x ./importCSV.sh
RUN chmod a+x ./runScript.sh

CMD ["cron", "-f"]